name: Java CI Junit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: macos-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Установка JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'

      - name: Установка прав на Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Gradle test
        run: ./gradlew clean myTags -x test -DcustomTags="UI,API"
        env:
          BROWSER_NAME: chrome
          BROWSER_OPTIONS_CHROME: --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080
          RUN_CI: true

      - name: Генерация отчета Allure
        if: always()
        run: ./gradlew allureReport

      - name: Проверка содержимого Allure-отчета
        if: always()
        run: |
          ls -la build/reports/allure-report || echo "Папка allure-report пуста или отсутствует"
          if [ -f "build/reports/allure-report/index.html" ]; then
            echo "Файл index.html найден"
          else
            echo "Ошибка: Файл index.html не найден в build/reports/allure-report"
            exit 1
          fi

      - name: Загрузка результатов Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results/
          retention-days: 14

      - name: Загрузка отчета Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report/
          retention-days: 14

      - name: Добавление файла .nojekyll
        if: always()
        run: |
          touch build/reports/allure-report/.nojekyll
          echo "Создан файл .nojekyll для GitHub Pages"

      - name: Публикация отчета Allure на GitHub Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          branch: gh-pages
          folder: build/reports/allure-report
          clean: true
          clean-exclude: |
            .nojekyll
          single-commit: true
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com

      - name: Отображение ссылки на отчет Allure
        if: always()
        run: |
          echo "URL отчета Allure: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"