name: Java CI Junit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: macos-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Установка JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'

      - name: Установка прав на Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Gradle test
        run: ./gradlew clean myTags -x test -DcustomTags="UI,API"
        env:
          BROWSER_NAME: chrome
          BROWSER_OPTIONS_CHROME: --remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080
          RUN_CI: true

      - name: Генерация отчета Allure
        if: always()
        run: ./gradlew allureReport

      - name: Загрузка результатов Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: build/allure-results/
          retention-days: 14

      - name: Загрузка отчета Allure
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: build/reports/allure-report/
          retention-days: 14